name: Sentiment Analysis CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 16
  PYTHON_VERSION: 3.8

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      lambda: ${{ steps.filter.outputs.lambda }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend:
            - 'frontend/**'
          lambda:
            - 'lambda/**'

    - name: Debug Changes Detection
      run: |
        echo "Frontend change detected: ${{ steps.filter.outputs.frontend }}"
        echo "Lambda change detected: ${{ steps.filter.outputs.lambda }}"

  security-scan:
    needs: changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install frontend dependencies
      if: ${{ needs.changes.outputs.frontend == 'true' }}
      working-directory: frontend
      run: |
        npm ci

    - name: Run Snyk to check for vulnerabilities (Frontend)
      if: ${{ needs.changes.outputs.frontend == 'true' }}
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --file=frontend/package.json --severity-threshold=high

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      if: ${{ needs.changes.outputs.lambda == 'true' }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build custom Docker image for Snyk
      if: ${{ needs.changes.outputs.lambda == 'true' }}
      run: |
        cat <<EOF > Dockerfile
        FROM snyk/snyk:python
        COPY lambda/requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        EOF
        docker build -t custom-snyk-python .

    - name: Run Snyk to check for vulnerabilities (Lambda)
      if: ${{ needs.changes.outputs.lambda == 'true' }}
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        docker run --rm \
          -e SNYK_TOKEN \
          -v ${PWD}:/app \
          -w /app \
          custom-snyk-python \
          snyk test --file=lambda/requirements.txt --severity-threshold=high

  test-frontend:
    needs: [changes, security-scan]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - name: Install dependencies
      working-directory: frontend
      run: npm ci
    - name: Run tests
      working-directory: frontend
      run: npm test

  test-lambda:
    needs: [changes, security-scan]
    if: ${{ needs.changes.outputs.lambda == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        cd lambda
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        SAGEMAKER_ENDPOINT_NAME: 'mock-endpoint'
      run: |
        cd lambda
        pytest

  build-and-deploy:
    needs: [test-frontend, test-lambda]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Debug Outputs
    - name: Debug Outputs
      run: |
        echo "Lambda change output from changes job: ${{ needs.changes.outputs.lambda }}"

    # Frontend build and deploy
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        echo 'REACT_APP_API_GATEWAY_ENDPOINT=${{ secrets.API_GATEWAY_ENDPOINT }}' > .env
        npm run build
    
    # Lambda build
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build Lambda
      run: |
        cd lambda
        pip install -r requirements.txt -t .
        zip -r ../lambda_function.zip .
    
    # Debug Lambda Artifact
    - name: Verify Lambda Artifact
      run: |
        ls -la lambda_function.zip

    # AWS configuration and deployment
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Deploy Lambda
      run: |
        MAX_RETRIES=5
        RETRY_INTERVAL=10
        for i in $(seq 1 $MAX_RETRIES); do
          if aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://lambda_function.zip; then
            echo "Lambda function updated successfully"
            break
          else
            if [ $i -eq $MAX_RETRIES ]; then
              echo "Failed to update Lambda function after $MAX_RETRIES attempts"
              exit 1
            fi
            echo "Update failed, retrying in $RETRY_INTERVAL seconds..."
            sleep $RETRY_INTERVAL
          fi
        done
    - name: Update Lambda configuration
      run: |
        MAX_RETRIES=5
        RETRY_INTERVAL=10
        for i in $(seq 1 $MAX_RETRIES); do
          if aws lambda update-function-configuration --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --environment "Variables={SAGEMAKER_ENDPOINT_NAME=${{ secrets.SAGEMAKER_ENDPOINT_NAME }}}"; then
            echo "Lambda function configuration updated successfully"
            break
          else
            if [ $i -eq $MAX_RETRIES ]; then
              echo "Failed to update Lambda function configuration after $MAX_RETRIES attempts"
              exit 1
            fi
            echo "Update failed, retrying in $RETRY_INTERVAL seconds..."
            sleep $RETRY_INTERVAL
          fi
        done

      

  # notify:
  #   needs: build-and-deploy
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Notify Slack
  #     uses: 8398a7/action-slack@v3
  #     with:
  #       status: ${{ job.status }}
  #       text: Deployment ${{ job.status == 'success' && 'succeeded' || 'failed' }}!
  #       webhook_url: ${{ secrets.SLACK_WEBHOOK }}
